"use client";

import { useMemo, useState } from "react";

type Role = "Customer" | "Pro" | "Admin";
type CustomerView = "Home" | "My Jobs" | "Post" | "Inbox" | "Profile";
type ProView = "Leads" | "Quotes" | "Jobs" | "Earnings" | "Profile";
type AdminView = "Overview" | "Verification" | "Marketplace" | "Payments" | "Catalog";
type JobStatus = "Open" | "Quoted" | "Hired" | "In Progress" | "Completed" | "Cancelled";

type Job = { id: string; title: string; detail: string; status: JobStatus; quotes: number; views: number; price: string; date: string };
type Quote = { id: string; pro: string; initials: string; rating: string; reviews: number; price: string; timeline: string; ai?: boolean };

const jobs: Job[] = [
  { id: "TL-1048", title: "Kitchen sink leak", detail: "Under-cabinet leak · 2 photos", status: "Quoted", quotes: 2, views: 18, price: "$180–$320", date: "Today" },
  { id: "TL-1036", title: "Replace bathroom faucet", detail: "Main floor · Flexible timing", status: "Hired", quotes: 4, views: 23, price: "$220", date: "Mar 18" },
  { id: "TL-1021", title: "Outdoor tap winterization", detail: "Front garden · Completed", status: "Completed", quotes: 3, views: 14, price: "$95", date: "Mar 02" },
  { id: "TL-0994", title: "Slow shower drain", detail: "Guest bathroom · Cancelled", status: "Cancelled", quotes: 1, views: 6, price: "$120", date: "Feb 24" },
];
const quotes: Quote[] = [
  { id: "q1", pro: "Northline Plumbing", initials: "NP", rating: "4.9", reviews: 86, price: "$245", timeline: "Tomorrow · 2 hrs", ai: true },
  { id: "q2", pro: "AquaFix Services", initials: "AS", rating: "4.8", reviews: 54, price: "$285", timeline: "Thursday · 90 min" },
];
const navIcons: Record<string, string> = { Home: "grid", "My Jobs": "briefcase", Post: "plus", Inbox: "chat", Profile: "user", Leads: "compass", Quotes: "file", Jobs: "calendar", Earnings: "chart", Overview: "grid", Verification: "shield", Marketplace: "briefcase", Payments: "card", Catalog: "sliders" };

function Icon({ name, size = 17 }: { name: string; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></>,
    briefcase: <><rect x="3" y="7" width="18" height="13" rx="2" /><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18M10 12v2h4v-2" /></>,
    plus: <><circle cx="12" cy="12" r="9" /><path d="M12 8v8M8 12h8" /></>,
    chat: <><path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 9 9 0 0 1-4-.9L4 20l1-3.5a7 7 0 0 1-1-4c0-4.1 3.6-7.5 8-7.5s8 2.9 8 6.5Z" /><path d="M8 11h.01M12 11h.01M16 11h.01" /></>,
    user: <><circle cx="12" cy="8" r="3.5" /><path d="M5 21a7 7 0 0 1 14 0" /></>,
    compass: <><circle cx="12" cy="12" r="9" /><path d="m15.5 8.5-2 5-5 2 2-5 5-2Z" /></>,
    file: <><path d="M6 3h9l3 3v15H6z" /><path d="M14 3v4h4M9 12h6M9 16h6" /></>,
    calendar: <><rect x="3" y="5" width="18" height="16" rx="2" /><path d="M16 3v4M8 3v4M3 10h18" /></>,
    chart: <><path d="M4 19V5M4 19h17" /><path d="m7 15 4-4 3 2 5-7" /></>,
    shield: <><path d="M12 3 20 6v5c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V6l8-3Z" /><path d="m8 12 2.5 2.5L16 9" /></>,
    card: <><rect x="3" y="5" width="18" height="14" rx="2" /><path d="M3 10h18M7 15h3" /></>,
    sliders: <><path d="M4 6h16M4 12h16M4 18h16" /><circle cx="8" cy="6" r="2" /><circle cx="16" cy="12" r="2" /><circle cx="10" cy="18" r="2" /></>,
    bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" /></>,
    arrow: <><path d="M5 12h14M13 6l6 6-6 6" /></>,
    check: <path d="m5 12 4 4L19 7" />,
    spark: <><path d="m12 3 1.4 5.6L19 10l-5.6 1.4L12 17l-1.4-5.6L5 10l5.6-1.4L12 3Z" /><path d="m19 16 .6 2.4L22 19l-2.4.6L19 22l-.6-2.4L16 19l2.4-.6L19 16Z" /></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name] ?? paths.grid}</svg>;
}

function Status({ status }: { status: JobStatus }) {
  const cls = status === "In Progress" ? "progress" : status.toLowerCase();
  return <span className={`status ${cls}`}><span>•</span>{status}</span>;
}

function JobRows({ onPost }: { onPost: () => void }) {
  return <section className="card card-pad"><div className="section-head"><h2>Recent jobs</h2><button className="link-button" onClick={onPost}>View all <Icon name="arrow" size={13} /></button></div>{jobs.slice(0, 3).map((job) => <article className="job-row" key={job.id}><div className="job-icon"><Icon name="briefcase" /></div><div className="job-main"><div className="job-title">{job.title}</div><div className="job-meta">{job.id} · {job.detail}</div></div><Status status={job.status} /><div className="job-meta desktop-only">{job.date}</div></article>)}</section>;
}

function CustomerHome({ setView }: { setView: (view: CustomerView) => void }) {
  return <><div className="hero"><div><p className="eyebrow">Customer dashboard</p><h1>Good morning, Alex</h1><p className="subtitle">Get your home sorted by a trusted local pro.</p></div><button className="primary" onClick={() => setView("Post")}><Icon name="plus" size={15} /> Post a new job</button></div><div className="grid stats-grid"><div className="card stat-card"><div className="stat-label">Active jobs</div><div className="stat-value">2</div><div className="stat-foot"><span>↗ 1</span> this week</div></div><div className="card stat-card"><div className="stat-label">Quotes received</div><div className="stat-value">6</div><div className="stat-foot"><span>↗ 24%</span> vs last month</div></div><div className="card stat-card"><div className="stat-label">Completed jobs</div><div className="stat-value">8</div><div className="stat-foot"><span>100%</span> satisfaction</div></div><div className="card stat-card"><div className="stat-label">Saved pros</div><div className="stat-value">4</div><div className="stat-foot"><span>★</span> top rated</div></div></div><div className="grid body-grid"><JobRows onPost={() => setView("My Jobs")} /><aside><div className="card cta-panel"><h2>Need a hand around the house?</h2><p>Tell us what’s going on. Our AI will help create a clear job brief for the right local pros.</p><button className="primary" onClick={() => setView("Post")}>Start with AI <Icon name="spark" size={14} /></button></div><div className="card tip-card"><h3>How TradeLink protects you</h3><div className="tip-row"><div className="tip-dot"><Icon name="shield" size={14} /></div><div><strong>Verified pros</strong><div className="job-meta">Licenses and insurance checked</div></div></div><div className="tip-row"><div className="tip-dot"><Icon name="card" size={14} /></div><div><strong>Secure payments</strong><div className="job-meta">Funds held until the job is done</div></div></div></div></aside></div></>;
}

function Scoper({ onDone }: { onDone: () => void }) {
  const [message, setMessage] = useState("");
  const [sent, setSent] = useState(false);
  return <div className="scoper"><div className="hero"><div><p className="eyebrow">AI scoper</p><h1>Let’s understand the job</h1><p className="subtitle">A few quick questions help us send a clearer brief to trusted pros.</p></div><button className="secondary" onClick={onDone}>Use guided wizard</button></div><section className="card scoper-window"><div className="scoper-top"><div className="pro-line"><div className="pro-avatar"><Icon name="spark" size={17} /></div><div><h3 style={{ margin: 0 }}>TradeLink AI</h3><div className="job-meta">Usually replies instantly</div></div></div><span className="status open">● Online</span></div><div className="chat-body"><div className="bubble ai">Hi Alex — describe what’s going on in your own words. For example: <strong>“my kitchen sink is leaking under the cabinet.”</strong></div>{sent && <div className="bubble user">{message}</div>}<div className="bubble ai">Thanks, I’ve got it. Is the water leak constant, or does it happen when the tap is running?</div>{sent && <><div className="bubble user">It happens when the tap is running. It’s a standard kitchen sink in a condo.</div><div className="bubble ai"><strong>Here’s what I understand.</strong> You need a kitchen faucet or supply connection checked and repaired. I’ll flag this as a normal-priority plumbing visit and share your photos with nearby pros.</div><div className="spec-grid"><div className="spec-item"><div className="spec-label">Service type</div><div className="spec-value">Kitchen plumbing repair</div></div><div className="spec-item"><div className="spec-label">Urgency</div><div className="spec-value">Within a week</div></div><div className="spec-item"><div className="spec-label">Property</div><div className="spec-value">Condo · Kitchen</div></div><div className="spec-item"><div className="spec-label">Access notes</div><div className="spec-value">Under-sink cabinet</div></div></div><div className="estimate"><div><span>Indicative estimate</span><strong>$180–$320 CAD</strong><span>Typical duration · 1–2 hours</span></div><button className="primary" onClick={onDone}>Confirm job spec <Icon name="arrow" size={14} /></button></div></>}</div><div className="chat-input"><input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Describe your home repair…" onKeyDown={(e) => { if (e.key === "Enter") setSent(true); }} /><button className="primary" onClick={() => setSent(true)} aria-label="Send message"><Icon name="arrow" size={16} /></button></div></section></div>;
}

function CustomerJobs({ setView }: { setView: (view: CustomerView) => void }) {
  const [hired, setHired] = useState(false);
  return <><div className="hero"><div><p className="eyebrow">My jobs</p><h1>Keep every repair moving</h1><p className="subtitle">Track quotes, appointments, payments and reviews in one place.</p></div><button className="primary" onClick={() => setView("Post")}><Icon name="plus" size={15} /> Post a job</button></div><div className="pill-tabs"><button className="active">All jobs <span>4</span></button><button>Open <span>1</span></button><button>In progress <span>1</span></button><button>Completed <span>1</span></button></div><div className="grid" style={{ gap: 12 }}>{jobs.map((job) => <article className="card card-pad" key={job.id}><div className="section-head"><div><div className="job-title">{job.title}</div><div className="job-meta">{job.id} · Posted {job.date}</div></div><Status status={hired && job.id === "TL-1048" ? "Hired" : job.status} /></div><div className="job-meta" style={{ margin: "12px 0 16px" }}>{job.detail}</div><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}><span className="job-meta">{job.views} views · {job.quotes} quote{job.quotes !== 1 ? "s" : ""} · <strong style={{ color: "var(--navy)" }}>{job.price}</strong></span>{job.id === "TL-1048" && !hired ? <button className="primary" onClick={() => setHired(true)}>Compare quotes <Icon name="arrow" size={13} /></button> : <button className="secondary" onClick={() => setView("Inbox")}>{hired && job.id === "TL-1048" ? "View job tracker" : "View details"}</button>}</div>{hired && job.id === "TL-1048" && <div className="timeline"><div className="timeline-step done"><div className="timeline-dot" /><div><div className="timeline-label">Deposit paid · Northline Plumbing hired</div><div className="timeline-date">Just now · $73.50 held securely</div></div></div><div className="timeline-step current"><div className="timeline-dot" /><div><div className="timeline-label">Schedule your visit</div><div className="timeline-date">Choose a time with your pro</div></div></div><div className="timeline-step"><div className="timeline-dot" /><div><div className="timeline-label">Job completed</div><div className="timeline-date">Payment releases after confirmation</div></div></div></div>}</article>)}</div></>;
}

function QuotesView({ onHire }: { onHire: () => void }) { return <><div className="hero"><div><p className="eyebrow">Kitchen sink leak · TL-1048</p><h1>Compare your quotes</h1><p className="subtitle">Two verified pros reviewed your job brief. Your exact address stays private until you hire.</p></div><span className="status quoted">● 2 quotes received</span></div><div className="notice" style={{ marginBottom: 16 }}><Icon name="shield" size={14} /> Payments are protected. A 30% deposit is held securely until the job is complete.</div><div className="grid" style={{ gridTemplateColumns: "repeat(2, minmax(0, 1fr))" }}>{quotes.map((quote) => <article className="card quote-card" key={quote.id}><div className="quote-head"><div className="pro-line"><div className="pro-avatar">{quote.initials}</div><div><h3 style={{ margin: 0 }}>{quote.pro}</h3><div className="job-meta"><span className="stars">★★★★★</span> {quote.rating} · {quote.reviews} reviews</div></div></div><span className="verified"><Icon name="check" size={13} /> Verified</span></div>{quote.ai && <div style={{ marginTop: 16 }}><span className="ai-badge"><Icon name="spark" size={10} /> AI-DRAFTED QUOTE</span></div>}<div className="quote-price">{quote.price} <small>CAD total</small></div><div className="quote-meta"><span><Icon name="calendar" size={12} /> {quote.timeline}</span><span><Icon name="shield" size={12} /> 90-day warranty</span></div><p className="subtitle" style={{ fontSize: 11 }}>Includes diagnosis, resealing supply connection, and cleanup. Materials allowance included.</p><div className="quote-actions"><button className="secondary">View storefront</button><button className="primary" onClick={onHire}>Hire this pro <Icon name="arrow" size={13} /></button></div></article>)}</div></>; }

function ProView({ view, setView }: { view: ProView; setView: (view: ProView) => void }) {
  const [sent, setSent] = useState(false);
  const proJobs = [{ title: "Kitchen sink leak", area: "Riverdale · 3.2 km", score: "94", range: "$180–$320", time: "Posted 18 min ago" }, { title: "Water heater inspection", area: "Leslieville · 5.8 km", score: "88", range: "$120–$220", time: "Posted 1 hr ago" }, { title: "Bathroom faucet replacement", area: "The Junction · 7.1 km", score: "81", range: "$160–$260", time: "Posted 3 hrs ago" }];
  if (view === "Leads") return <><div className="hero"><div><p className="eyebrow">Pro workspace</p><h1>Good morning, Jordan</h1><p className="subtitle">3 new plumbing jobs match your profile and radius.</p></div><span className="status completed">● Available for work</span></div><div className="notice" style={{ marginBottom: 18 }}><Icon name="spark" size={14} /> Your fit score prioritizes jobs where your skills, availability, and location line up.</div><div className="grid" style={{ gap: 12 }}>{proJobs.map((lead) => <article className="card card-pad" key={lead.title}><div className="section-head"><div><div className="job-title">{lead.title}</div><div className="job-meta">{lead.area} · {lead.time}</div></div><div style={{ textAlign: "right" }}><strong style={{ color: "var(--blue)", fontSize: 20 }}>{lead.score}</strong><div className="job-meta">fit score</div></div></div><div style={{ display: "flex", gap: 7, flexWrap: "wrap", margin: "14px 0" }}><span className="status open">Near you</span><span className="status completed">Strong skill match</span><span className="status quoted">Customer estimate {lead.range}</span></div><p className="subtitle" style={{ fontSize: 11 }}>Leaking connection below a kitchen sink. Condo access, normal urgency. Exact address revealed after hire.</p><div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}><button className="secondary">View lead</button><button className="primary" onClick={() => setView("Quotes")}>Create quote <Icon name="arrow" size={13} /></button></div></article>)}</div></>;
  if (view === "Quotes") return <><div className="hero"><div><p className="eyebrow">Quote builder</p><h1>Turn a good lead into a clear quote</h1><p className="subtitle">Itemize the work so customers know exactly what they’re accepting.</p></div><button className="primary" onClick={() => setSent(true)}>{sent ? "Quote sent" : "Send quote"} <Icon name="arrow" size={13} /></button></div><section className="card card-pad" style={{ maxWidth: 760 }}><div className="section-head"><div><h2>Kitchen sink leak</h2><div className="job-meta">TL-1048 · Customer estimate $180–$320</div></div><button className="secondary" onClick={() => setSent(false)}><Icon name="spark" size={13} /> AI draft</button></div>{sent && <div className="status completed" style={{ marginBottom: 14 }}><Icon name="check" size={13} /> Quote sent · platform commission of 15% shown below</div>}<div className="grid" style={{ gap: 10 }}><div className="spec-item"><div className="spec-label">Labor</div><div className="spec-value">Leak diagnosis & repair <span style={{ float: "right" }}>$160</span></div></div><div className="spec-item"><div className="spec-label">Materials allowance</div><div className="spec-value">Supply line + sealant <span style={{ float: "right" }}>$55</span></div></div><div className="spec-item"><div className="spec-label">Timeline</div><div className="spec-value">Tomorrow · 2 hours</div></div></div><div className="estimate" style={{ marginTop: 18 }}><div><span>Customer total</span><strong>$245 CAD</strong><span>Estimated payout after 15% commission · $208.25</span></div><span className="ai-badge">VALID 7 DAYS</span></div></section></>;
  if (view === "Earnings") return <><div className="hero"><div><p className="eyebrow">Earnings</p><h1>Know what you take home</h1><p className="subtitle">Transparent payouts, with your 15% platform commission shown up front.</p></div><button className="secondary">Payout settings</button></div><div className="grid stats-grid"><div className="card stat-card"><div className="stat-label">Available to withdraw</div><div className="stat-value">$1,284</div><div className="stat-foot">Next payout · Friday</div></div><div className="card stat-card"><div className="stat-label">Pending release</div><div className="stat-value">$208</div><div className="stat-foot">1 active job</div></div><div className="card stat-card"><div className="stat-label">Gross this month</div><div className="stat-value">$2,460</div><div className="stat-foot"><span>↗ 18%</span> vs February</div></div><div className="card stat-card"><div className="stat-label">Jobs completed</div><div className="stat-value">12</div><div className="stat-foot">4.9 average rating</div></div></div><section className="card card-pad"><div className="section-head"><h2>Payout history</h2><button className="link-button">Export CSV</button></div><div className="table-scroll"><table className="admin-table"><thead><tr><th>Date</th><th>Job</th><th>Gross</th><th>Commission</th><th>Net</th><th>Status</th></tr></thead><tbody><tr><td>Mar 15</td><td>Toilet repair</td><td>$180</td><td>-$27</td><td><strong>$153</strong></td><td><span className="status completed">Paid</span></td></tr><tr><td>Mar 08</td><td>Faucet replacement</td><td>$220</td><td>-$33</td><td><strong>$187</strong></td><td><span className="status completed">Paid</span></td></tr></tbody></table></div></section></>;
  return <><div className="hero"><div><p className="eyebrow">Profile & verification</p><h1>Build trust before the first visit</h1><p className="subtitle">Keep your storefront, documents, and availability up to date.</p></div><span className="status completed"><Icon name="check" size={12} /> Approved</span></div><div className="grid body-grid"><section className="card card-pad"><div className="section-head"><h2>Application tracker</h2><span className="verified">6 of 6 complete</span></div><div className="timeline"><div className="timeline-step done"><div className="timeline-dot" /><div><div className="timeline-label">Application submitted</div><div className="timeline-date">Mar 01</div></div></div><div className="timeline-step done"><div className="timeline-dot" /><div><div className="timeline-label">Documents reviewed</div><div className="timeline-date">License, insurance, ID verified</div></div></div><div className="timeline-step current"><div className="timeline-dot" /><div><div className="timeline-label">Profile live</div><div className="timeline-date">Available in Toronto East · 25 km radius</div></div></div></div></section><section className="card card-pad"><div className="section-head"><h2>Storefront</h2><button className="secondary"><Icon name="spark" size={13} /> AI profile builder</button></div><h3>Northline Plumbing</h3><p className="subtitle">Reliable residential plumbing, from small leaks to water heater installs. Serving Toronto homeowners with clear quotes and tidy work.</p><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><span className="status completed">Available</span><span className="status open">4.9 ★ · 86 reviews</span></div></section></div></>;
}

function AdminView({ view }: { view: AdminView }) {
  const [action, setAction] = useState("");
  if (view === "Verification") return <><div className="hero"><div><p className="eyebrow">Admin · Compliance</p><h1>Verification queue</h1><p className="subtitle">Review documents and keep the marketplace safe.</p></div><span className="status quoted">4 awaiting review</span></div><section className="card card-pad"><div className="filter-row"><input className="search" placeholder="Search applicant or document" /><button className="secondary">Filter: All</button></div><div className="table-scroll"><table className="admin-table"><thead><tr><th>Applicant</th><th>Trade</th><th>Documents</th><th>Submitted</th><th>Status</th><th>Action</th></tr></thead><tbody>{[["Maya Chen","Plumbing","3 files","Today","Under Review"],["Derek Hall","Plumbing","2 files","Yesterday","More Info Requested"],["Northline Plumbing","Plumbing","3 files","Mar 01","Approved"]].map((row) => <tr key={row[0]}><td><strong>{row[0]}</strong></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><span className={`status ${row[4] === "Approved" ? "completed" : row[4] === "More Info Requested" ? "progress" : "quoted"}`}>{row[4]}</span></td><td><button className="link-button" onClick={() => setAction(`${row[0]} reviewed`)}>{row[4] === "Approved" ? "View" : "Review"}</button></td></tr>)}</tbody></table></div>{action && <div className="notice" style={{ marginTop: 16 }}><Icon name="check" size={14} /> {action}. Mock action saved.</div>}</section></>;
  if (view === "Payments") return <><div className="hero"><div><p className="eyebrow">Admin · Finance</p><h1>Payments console</h1><p className="subtitle">Monitor holds, commissions, releases and refunds across TradeLink.</p></div><button className="secondary">Export CSV</button></div><div className="grid stats-grid"><div className="card stat-card"><div className="stat-label">GMV this month</div><div className="stat-value">$42.8k</div><div className="stat-foot"><span>↗ 12.4%</span> vs last month</div></div><div className="card stat-card"><div className="stat-label">Commission earned</div><div className="stat-value">$6.4k</div><div className="stat-foot">15% take rate</div></div><div className="card stat-card"><div className="stat-label">Funds on hold</div><div className="stat-value">$8.2k</div><div className="stat-foot">34 active bookings</div></div><div className="card stat-card"><div className="stat-label">Refunds this month</div><div className="stat-value">$620</div><div className="stat-foot">1.4% of GMV</div></div></div><section className="card card-pad"><div className="section-head"><h2>Recent transactions</h2><span className="status completed">● Live feed</span></div><div className="table-scroll"><table className="admin-table"><thead><tr><th>Transaction</th><th>Job</th><th>Customer</th><th>Amount</th><th>Commission</th><th>Status</th></tr></thead><tbody><tr><td><strong>TX-8821</strong></td><td>Kitchen sink leak</td><td>Alex Morgan</td><td>$73.50</td><td>$11.03</td><td><span className="status progress">Deposit held</span></td></tr><tr><td><strong>TX-8814</strong></td><td>Faucet replacement</td><td>Sam Lee</td><td>$220</td><td>$33</td><td><span className="status completed">Released</span></td></tr><tr><td><strong>TX-8807</strong></td><td>Toilet repair</td><td>Priya Shah</td><td>$153</td><td>$22.95</td><td><span className="status completed">Released</span></td></tr></tbody></table></div></section></>;
  if (view === "Catalog") return <><div className="hero"><div><p className="eyebrow">Admin · Service catalog</p><h1>Plumbing pricing rules</h1><p className="subtitle">These price bands power every indicative estimate customers see.</p></div><button className="primary"><Icon name="plus" size={15} /> Add job type</button></div><section className="card card-pad"><div className="table-scroll"><table className="admin-table"><thead><tr><th>Job type</th><th>Price band</th><th>Typical duration</th><th>Last updated</th><th>Status</th></tr></thead><tbody>{[["Faucet replacement","$120–$220","1–2 hrs","Today"],["Kitchen sink leak","$180–$320","1–2 hrs","Today"],["Toilet repair","$95–$180","1–2 hrs","Mar 12"],["Water heater install","$900–$1,600","5–8 hrs","Mar 10"],["Main drain unclog","$180–$450","2–4 hrs","Mar 10"],["Outdoor tap repair","$120–$250","1–2 hrs","Mar 08"]].map((row) => <tr key={row[0]}><td><strong>{row[0]}</strong></td><td>{row[1]} CAD</td><td>{row[2]}</td><td>{row[3]}</td><td><span className="status completed">Active</span></td></tr>)}</tbody></table></div></section></>;
  return <><div className="hero"><div><p className="eyebrow">Admin overview</p><h1>Marketplace health</h1><p className="subtitle">A clear view of growth, liquidity, and where customers need help.</p></div><span className="status completed">● All systems normal</span></div><div className="grid stats-grid"><div className="card stat-card"><div className="stat-label">GMV</div><div className="stat-value">$42.8k</div><div className="stat-foot"><span>↗ 12.4%</span> this month</div></div><div className="card stat-card"><div className="stat-label">Jobs posted</div><div className="stat-value">186</div><div className="stat-foot"><span>↗ 8.2%</span> this month</div></div><div className="card stat-card"><div className="stat-label">Hire rate</div><div className="stat-value">36.8%</div><div className="stat-foot"><span>↗ 4.1%</span> vs last month</div></div><div className="card stat-card"><div className="stat-label">Active users</div><div className="stat-value">1,248</div><div className="stat-foot"><span>↗ 14.6%</span> this month</div></div></div><div className="grid body-grid"><section className="card card-pad"><div className="section-head"><div><h2>Marketplace funnel</h2><div className="job-meta">Last 30 days</div></div><button className="secondary">30 days</button></div><div className="bar-chart">{[48,62,55,75,68,92,80,100,84,74,88,95].map((height, index) => <div className="bar" key={index} style={{ height: `${height}%` }}><span>{index + 1}</span></div>)}</div></section><section className="card card-pad"><div className="section-head"><h2>Needs attention</h2><span className="status progress">3 open</span></div><div className="tip-row"><div className="tip-dot"><Icon name="shield" size={14} /></div><div><strong>4 pros awaiting verification</strong><div className="job-meta">Oldest request · 2 days</div></div></div><div className="tip-row"><div className="tip-dot" style={{ color: "var(--red)", background: "var(--red-bg)" }}><Icon name="bell" size={14} /></div><div><strong>1 flagged job dispute</strong><div className="job-meta">Kitchen leak · TL-0986</div></div></div><div className="tip-row"><div className="tip-dot"><Icon name="chart" size={14} /></div><div><strong>Quote rate dipped 4%</strong><div className="job-meta">Review lead matching</div></div></div></section></div></>;
}

export default function Page() {
  const [role, setRole] = useState<Role>("Customer");
  const [customerView, setCustomerView] = useState<CustomerView>("Home");
  const [proView, setProView] = useState<ProView>("Leads");
  const [adminView, setAdminView] = useState<AdminView>("Overview");
  const [showQuotes, setShowQuotes] = useState(false);
  const nav = role === "Customer" ? ["Home", "My Jobs", "Post", "Inbox", "Profile"] : role === "Pro" ? ["Leads", "Quotes", "Jobs", "Earnings", "Profile"] : ["Overview", "Verification", "Marketplace", "Payments", "Catalog"];
  const current = role === "Customer" ? customerView : role === "Pro" ? proView : adminView;
  const displayTitle = useMemo(() => role === "Admin" ? "TradeLink Admin" : role === "Pro" ? "Pro workspace" : "TradeLink", [role]);
  const setCurrent = (item: string) => { if (role === "Customer") setCustomerView(item as CustomerView); else if (role === "Pro") setProView(item as ProView); else setAdminView(item as AdminView); };
  const render = () => { if (role === "Customer") { if (showQuotes) return <QuotesView onHire={() => { setShowQuotes(false); setCustomerView("My Jobs"); }} />; if (customerView === "Home") return <CustomerHome setView={setCustomerView} />; if (customerView === "Post") return <Scoper onDone={() => setShowQuotes(true)} />; if (customerView === "My Jobs") return <CustomerJobs setView={(view) => view === "Inbox" ? setShowQuotes(true) : setCustomerView(view)} />; return <><div className="hero"><div><p className="eyebrow">{customerView}</p><h1>{customerView === "Inbox" ? "Your conversations" : "Your TradeLink profile"}</h1><p className="subtitle">{customerView === "Inbox" ? "Chat unlocks after you hire a pro. Your kitchen sink repair is ready for a schedule." : "Keep your details and preferences up to date."}</p></div></div><div className="card card-pad"><div className="notice"><Icon name="chat" size={14} /> {customerView === "Inbox" ? "Northline Plumbing · Deposit paid · Choose a visit time to unlock chat." : "Alex Morgan · alex@example.com · Toronto, ON"}</div></div></>; } if (role === "Pro") return <ProView view={proView} setView={setProView} />; return <AdminView view={adminView} />; };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Icon name="arrow" size={17} /></span>TradeLink</div><div className="role-chip"><span>Viewing as</span><strong>{role}</strong></div><nav className="nav" aria-label="Primary navigation">{nav.map((item) => <button key={item} className={current === item ? "active" : ""} onClick={() => { setCurrent(item); setShowQuotes(false); }}><Icon name={navIcons[item]} size={16} />{item}{item === "Inbox" && <span style={{ marginLeft: "auto", background: "var(--blue)", color: "#fff", borderRadius: 99, padding: "2px 6px", fontSize: 9 }}>2</span>}</button>)}</nav><div className="sidebar-footer">Plumbing marketplace<br />Toronto region · CAD<br /><br />© 2025 TradeLink</div></aside><main className="main"><header className="topbar"><div className="topbar-title">{displayTitle}</div><div className="topbar-actions"><button className="icon-button" aria-label="Notifications"><Icon name="bell" size={17} /></button><button className="role-chip desktop-only" style={{ margin: 0, color: "var(--navy)", background: "#fff", borderColor: "var(--line)", gap: 10 }} onClick={() => setRole(role === "Customer" ? "Pro" : role === "Pro" ? "Admin" : "Customer")}><span>Switch role</span><strong>{role === "Customer" ? "Pro" : role === "Pro" ? "Admin" : "Customer"}</strong></button><div className="user-avatar">AM</div></div></header><div className="content">{render()}</div></main><nav className="mobile-tabs" aria-label="Mobile navigation">{nav.slice(0, 5).map((item) => <button key={item} className={current === item ? "active" : ""} onClick={() => { setCurrent(item); setShowQuotes(false); }}><Icon name={navIcons[item]} size={17} />{item}</button>)}</nav></div>;
}
